import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from "react";
import ReactDOM from "react-dom/client";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { BrowserRouter } from "react-router-dom";
import { Toaster } from "sonner";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { AppRouter } from "./router";
import { AuthProvider } from "./state/auth";
import "./styles.css";
const queryClient = new QueryClient();
const googleClientId = import.meta.env.VITE_GOOGLE_CLIENT_ID || "673073717912-6su2u0ofd04gial1gb321cdd9kbsk3fq.apps.googleusercontent.com";
ReactDOM.createRoot(document.getElementById("root")).render(_jsx(React.StrictMode, { children: _jsxs(QueryClientProvider, { client: queryClient, children: [_jsx(BrowserRouter, { children: _jsx(GoogleOAuthProvider, { clientId: googleClientId, children: _jsxs(AuthProvider, { children: [_jsx(AppRouter, {}), _jsx(Toaster, { richColors: true, position: "top-right" })] }) }) }), _jsx(ReactQueryDevtools, { initialIsOpen: false })] }) }));
