export const schemaStatements = [
  `CREATE TABLE clinics (
      id VARCHAR2(40) PRIMARY KEY,
      name VARCHAR2(150) NOT NULL,
      phone VARCHAR2(40),
      email VARCHAR2(150) NOT NULL UNIQUE,
      address VARCHAR2(250),
      working_hours CLOB,
      appointment_duration NUMBER(3) DEFAULT 30 NOT NULL,
      subscription_plan VARCHAR2(30) DEFAULT 'START' NOT NULL,
      subscription_status VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL,
      billing_cycle VARCHAR2(30) DEFAULT 'MONTHLY' NOT NULL,
      subscription_started_at TIMESTAMP,
      trial_ends_at TIMESTAMP,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
    )`,
  `CREATE TABLE users (
      id VARCHAR2(40) PRIMARY KEY,
      tenant_id VARCHAR2(40) NOT NULL REFERENCES clinics(id),
      first_name VARCHAR2(100) NOT NULL,
      last_name VARCHAR2(100) NOT NULL,
      email VARCHAR2(150) NOT NULL,
      phone VARCHAR2(40),
      password_hash VARCHAR2(255) NOT NULL,
      role VARCHAR2(30) NOT NULL,
      refresh_token_hash VARCHAR2(255),
      is_active NUMBER(1) DEFAULT 1 NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      CONSTRAINT users_tenant_email_uk UNIQUE (tenant_id, email)
    )`,
  `CREATE TABLE patients (
      id VARCHAR2(40) PRIMARY KEY,
      tenant_id VARCHAR2(40) NOT NULL REFERENCES clinics(id),
      first_name VARCHAR2(100) NOT NULL,
      last_name VARCHAR2(100) NOT NULL,
      document VARCHAR2(80),
      birth_date TIMESTAMP,
      phone VARCHAR2(40),
      whatsapp VARCHAR2(40),
      email VARCHAR2(150),
      address VARCHAR2(250),
      allergies CLOB,
      medical_history CLOB,
      notes CLOB,
      is_active NUMBER(1) DEFAULT 1 NOT NULL,
      deleted_at TIMESTAMP,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
    )`,
  `CREATE TABLE appointments (
      id VARCHAR2(40) PRIMARY KEY,
      tenant_id VARCHAR2(40) NOT NULL REFERENCES clinics(id),
      patient_id VARCHAR2(40) NOT NULL REFERENCES patients(id),
      professional_id VARCHAR2(40) NOT NULL REFERENCES users(id),
      start_at TIMESTAMP NOT NULL,
      end_at TIMESTAMP NOT NULL,
      duration_minutes NUMBER(4) NOT NULL,
      reason VARCHAR2(250) NOT NULL,
      status VARCHAR2(30) DEFAULT 'PENDING_CONFIRMATION' NOT NULL,
      confirmation_pending NUMBER(1) DEFAULT 1 NOT NULL,
      deleted_at TIMESTAMP,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
    )`,
  `CREATE TABLE clinical_notes (
      id VARCHAR2(40) PRIMARY KEY,
      tenant_id VARCHAR2(40) NOT NULL REFERENCES clinics(id),
      patient_id VARCHAR2(40) NOT NULL REFERENCES patients(id),
      professional_id VARCHAR2(40) NOT NULL REFERENCES users(id),
      appointment_id VARCHAR2(40),
      note_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      reason VARCHAR2(250) NOT NULL,
      diagnosis CLOB,
      procedure_text CLOB,
      indications CLOB,
      observations CLOB,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
    )`,
  `CREATE TABLE treatments (
      id VARCHAR2(40) PRIMARY KEY,
      tenant_id VARCHAR2(40) NOT NULL REFERENCES clinics(id),
      patient_id VARCHAR2(40) NOT NULL REFERENCES patients(id),
      professional_id VARCHAR2(40),
      type VARCHAR2(120) NOT NULL,
      description CLOB NOT NULL,
      status VARCHAR2(30) DEFAULT 'PLANNED' NOT NULL,
      estimated_cost NUMBER(12,2) DEFAULT 0 NOT NULL,
      final_cost NUMBER(12,2),
      start_date TIMESTAMP,
      end_date TIMESTAMP,
      deleted_at TIMESTAMP,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
    )`,
  `CREATE TABLE payments (
      id VARCHAR2(40) PRIMARY KEY,
      tenant_id VARCHAR2(40) NOT NULL REFERENCES clinics(id),
      patient_id VARCHAR2(40) NOT NULL REFERENCES patients(id),
      treatment_id VARCHAR2(40),
      amount NUMBER(12,2) NOT NULL,
      paid_at TIMESTAMP NOT NULL,
      method VARCHAR2(20) NOT NULL,
      observations CLOB,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
    )`,
  `CREATE TABLE follow_ups (
      id VARCHAR2(40) PRIMARY KEY,
      tenant_id VARCHAR2(40) NOT NULL REFERENCES clinics(id),
      patient_id VARCHAR2(40) NOT NULL REFERENCES patients(id),
      professional_id VARCHAR2(40),
      title VARCHAR2(150) NOT NULL,
      notes CLOB,
      due_date TIMESTAMP NOT NULL,
      frequency_days NUMBER(5),
      status VARCHAR2(30) DEFAULT 'PENDING' NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
    )`,
  `CREATE TABLE integration_configs (
      id VARCHAR2(40) PRIMARY KEY,
      tenant_id VARCHAR2(40) NOT NULL REFERENCES clinics(id),
      type VARCHAR2(50) NOT NULL,
      provider VARCHAR2(50) NOT NULL,
      config CLOB NOT NULL,
      is_enabled NUMBER(1) DEFAULT 0 NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
    )`,
  `CREATE TABLE audit_logs (
      id VARCHAR2(40) PRIMARY KEY,
      tenant_id VARCHAR2(40) NOT NULL REFERENCES clinics(id),
      user_id VARCHAR2(40),
      action VARCHAR2(80) NOT NULL,
      entity VARCHAR2(80) NOT NULL,
      entity_id VARCHAR2(40) NOT NULL,
      metadata CLOB,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
    )`,
  `CREATE INDEX idx_users_tenant_role ON users (tenant_id, role)`,
  `CREATE INDEX idx_patients_tenant_lastname ON patients (tenant_id, last_name)`,
  `CREATE INDEX idx_patients_tenant_document ON patients (tenant_id, document)`,
  `CREATE INDEX idx_appointments_tenant_start ON appointments (tenant_id, start_at)`,
  `CREATE INDEX idx_appointments_tenant_prof_start ON appointments (tenant_id, professional_id, start_at)`,
  `CREATE INDEX idx_treatments_tenant_patient_status ON treatments (tenant_id, patient_id, status)`,
  `CREATE INDEX idx_payments_tenant_patient_paid ON payments (tenant_id, patient_id, paid_at)`,
  `CREATE INDEX idx_followups_tenant_due ON follow_ups (tenant_id, due_date)`,
  `CREATE INDEX idx_integrations_tenant_type ON integration_configs (tenant_id, type)`,
  `CREATE INDEX idx_audit_tenant_created ON audit_logs (tenant_id, created_at)`,
];
